[package]
name = "apollo-scanner"
version = "3.0.0"
edition = "2021"
authors = ["Apollo"]
description = "Ultimate Network Scanner"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
chrono = { version = "0.4", features = ["serde"] }
cidr = "0.2"
trust-dns-resolver = "0.22"
pnet = "0.31"
socket2 = "0.4"
rand = "0.8"
openssl = "0.10"
nix = "0.26"
libc = "0.2"
macaddr = "1.0"
base64 = "0.21"
regex = "1.0"
url = "2.0"
